-- Drop all tables if tables have been created earlier
DROP TABLE CHEF CASCADE CONSTRAINT purge;
DROP TABLE SPECIALITY CASCADE CONSTRAINT purge;
DROP TABLE PARTY CASCADE CONSTRAINT purge;
DROP TABLE CLIENT CASCADE CONSTRAINT purge;
DROP TABLE FEEDBACK CASCADE CONSTRAINT purge;
DROP TABLE CHEFPARTY CASCADE CONSTRAINT purge;
